# Generated by Django 5.0.6 on 2025-02-26 09:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                ("demo_link", models.URLField(blank=True, max_length=2000, null=True)),
                (
                    "source_link",
                    models.URLField(blank=True, max_length=2000, null=True),
                ),
                ("date_created", models.DateField(auto_now_add=True)),
            ],
        ),
    ]
