# Generated by Django 5.0.6 on 2025-02-26 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_tag_project_vote_ratio_project_vote_total_review_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="value",
            field=models.CharField(
                choices=[("up", "Up vote"), ("down", "Down vote")], max_length=200
            ),
        ),
    ]
